name: Python tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "Debug: list repo"
        run: |
          echo "PWD: $(pwd)"
          echo "ROOT files:"
          ls -la
          echo "tests dir:"
          ls -la tests || true
          echo "Python sys.path:"
          python -c "import sys, pprint; pprint.pprint(sys.path)"
          echo "pytest version:"
          python -c "import pytest, sys; print(pytest.__version__ if 'pytest' in sys.modules or hasattr(pytest, '__version__') else 'pytest not imported')"

      - name: Run tests
        run: |
          python -m pytest -q